# .bashrc settings

## check for an interative session
[ -z "$PS1" ] && return

## set archlinux style prompt
PS1='[\u@\h \W]\$ '

## history settings
unset HISTFILESIZE
HISTSIZE=10000
PROMPT_COMMAND="history -a"
export HISTSIZE PROMPT_COMMAND
shopt -s histappend

## set vi behavior on the command line
set -o vi

## turn on ls color support
CLICOLOR="YES"; export CLICOLOR

## set default editor
EDITOR="vim"
export EDITOR

## aliases
source ~/.sh_aliases

## additional user ENVs
[ -e ~/.user-env ] && source ~/.user-env
