# .bashrc settings

# check for an interative session
[ -z "$PS1" ] && return

# set archlinux style prompt
PS1='[\u@\h \W]\$ '

# history settings
unset HISTFILESIZE
HISTSIZE=10000
PROMPT_COMMAND="history -a"
export HISTSIZE PROMPT_COMMAND
shopt -s histappend

# set vi behavior on the command line
set -o vi

# turn on ls color support
CLICOLOR="YES"; export CLICOLOR

# add local paths to path for homebrew etc
PATH="/usr/local/bin:/usr/local/sbin:${PATH}"

# set default editor
EDITOR="vim"
export EDITOR

# aliases
alias grep='grep --color=auto'
alias l='ls'
alias la='ls -ah'
alias ll='ls -lah'
alias cd..='cd ..'

## mac only aliases
if [ $(uname) = "Darwin" ]; then
	alias flushdns='dscacheutil -flushcache;sudo killall -HUP mDNSResponder'
	alias shadowno='defaults write com.apple.screencapture disable-shadow -bool true && killall SystemUIServer'
	alias shadowyes='defaults delete com.apple.screencapture disable-shadow && killall SystemUIServer'
	alias sortlaunchpad='defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock'
	alias brewdoc='brew update && brew doctor'
	alias brewup='brew update && brew doctor && brew upgrade; brew cleanup; brew prune'
	alias speedtest='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
	### bash completion
	if [ -f $(brew --prefix)/etc/bash_completion ]; then
		. $(brew --prefix)/etc/bash_completion
	fi
fi


## mac development
if [ $(uname) = "Darwin" ]; then
	### python
	#export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
	#alias sv='source venv/bin/activate'

	### django
	#source $HOME/mac-prefs/django_bash_completion

	### marks
	#export MARKPATH=$HOME/.marks
	#function jump { 
		#cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
	#}
	#function mark { 
		#mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
	#}
	#function unmark { 
		#rm -i "$MARKPATH/$1"
	#}

	#### osx
	#function marks {
		#\ls -l "$MARKPATH" | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
	#}

	#_completemarks() {
	  #local curw=${COMP_WORDS[COMP_CWORD]}
	  #local wordlist=$(find $MARKPATH -type l | sed -En 's/(.*)\/.(marks)\/(.*)/\3/p')
	  #COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
	  #return 0
	#}

	#complete -F _completemarks jump unmark

	### Added by the Heroku Toolbelt
	export PATH="/usr/local/heroku/bin:$PATH"
fi


## man page color and search hilighting
export PAGER="less"
man() {
	env \
		LESS_TERMCAP_mb=$(printf "\e[1;31m") \
		LESS_TERMCAP_md=$(printf "\e[1;31m") \
		LESS_TERMCAP_me=$(printf "\e[0m") \
		LESS_TERMCAP_se=$(printf "\e[0m") \
		LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
		LESS_TERMCAP_ue=$(printf "\e[0m") \
		LESS_TERMCAP_us=$(printf "\e[1;32m") \
		man "$@"
}
