# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="digitalnomad"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

## default plugins
plugins=(git tmux vi-mode)

## mac plugins
if [ $(uname) = "Darwin" ]; then
	plugins=(bundler git jump tmux tmuxinator vagrant vi-mode virtualenvwrapper)
fi

# User configuration

######################################
### see .zshenv for PATH defintion ###
######################################
#export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


########################################
#####            CUSTOM            #####
########################################

## add local paths to path for homebrew etc
path=(
    /usr/local/bin
    /usr/local/sbin
    $path
)
export path

## set default editor
EDITOR="vim"
export EDITOR

### vi mode fixes
bindkey "^?" backward-delete-char

## don't share history between tabs
unsetopt share_history

## command specific history search
### emacs bindings
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
### vim bindings
bindkey -a k history-beginning-search-backward
bindkey -a j history-beginning-search-forward

## Emacs Fixes
#export TERM=xterm-256color

## set LSCOLORS to system default
unset LSCOLORS 

## aliases
alias ez='vim ~/.zshrc'
alias grep='grep --color=auto'
alias l='ls'
alias la='ls -lah'
alias ll='ls -lh'
alias cd..='cd ..'
### mac only aliases
if [ $(uname) = "Darwin" ]; then
	alias flushdns='dscacheutil -flushcache;sudo killall -HUP mDNSResponder'
	alias shadowno='defaults write com.apple.screencapture disable-shadow -bool true && killall SystemUIServer'
	alias shadowyes='defaults delete com.apple.screencapture disable-shadow && killall SystemUIServer'
	alias sortlaunchpad='rm ~/Library/Application\ Support/Dock/*.db ; killall Dock'
	alias brewdoc='brew update && brew doctor'
	alias brewup='brew update && brew doctor && brew upgrade; brew cleanup; brew prune'
	#alias speedtest='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
	alias speedtest='speedtest-cli'
	#alias scheme="rlwrap scheme"
	#alias scheme="rlwrap scheme-r5rs"
	### stop correction intrusion
	alias sass='nocorrect sass'
	alias vagrant='nocorrect vagrant'
	alias chef='nocorrect chef'
	alias knife='nocorrect knife'

#### mac development
	### homebrew
	export HOMEBREW_GITHUB_API_TOKEN=4da4afd78bcd05ec169285a1dfca84a27481e961
	### python
	#export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
	#alias sv='source venv/bin/activate'
	#alias mkvirtualenv2='mkvirtualenv -p /usr/local/bin/python2.7'
	#alias mkvirtualenv3='mkvirtualenv -p /usr/local/bin/python3'
	export WORKON_HOME=~/.virtualenvs
	export PROJECT_HOME=~/src
	#source /usr/local/bin/virtualenvwrapper.sh
	### vagrant
	alias vssh='vagrant up && vagrant ssh'
	### ruby
	source /usr/local/opt/chruby/share/chruby/chruby.sh
	source /usr/local/opt/chruby/share/chruby/auto.sh
	#### set default ruby when no .ruby-version is present
	chruby ruby-2.2

#### mac blogging
	cryogen-publish(){
		curdir=$(pwd)
		cd ../public/ || echo "### You must run this from the resources/templates directory of your Cryogen site! ###"
		git add --all
		git commit -a -m "site content update" && git push
		cd $curdir
}

fi

## update dot files
update-dotfiles(){
	curdir=$(pwd)
	cd ~/dotfiles && git pull && sh deploy.sh
	cd $curdir
}

## man page color and search hilighting
export PAGER="less"
man() {
	env \
		LESS_TERMCAP_mb=$(printf "\e[1;31m") \
		LESS_TERMCAP_md=$(printf "\e[1;31m") \
		LESS_TERMCAP_me=$(printf "\e[0m") \
		LESS_TERMCAP_se=$(printf "\e[0m") \
		LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
		LESS_TERMCAP_ue=$(printf "\e[0m") \
		LESS_TERMCAP_us=$(printf "\e[1;32m") \
		man "$@"
}

## update settings and load tmux automagically on servers intelligently
if [ ! $(uname) = "Darwin" ] && [ ! $(id -u) = 0 ]; then
	case "$-" in *i*) [ -z $TMUX ] && if tmux has; then tmux attach; else tmux new; fi && exit 0; esac;
fi
