require("core.plugins_config.colorscheme")
require("core.plugins_config.telescope")
require("core.plugins_config.treesitter")
require("core.plugins_config.mini")
require("core.plugins_config.lsp")
require("core.plugins_config.comment")
require("core.plugins_config.fugitive")
